DjangoRed/AccountsApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts_app'

urlpatterns = [
    path('profile/', views.user_profile, name='profile'),
    path('register/', views.register, name='register'),

    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    # change password urls
    path(
        'password-change/',
        views.password_change,
        name='password_change'
    ),
    path(
        'password-change/done/',
        views.password_change_done,
        name='password_change_done'
    ),

    # reset password urls
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'
    ),
    path(
        'password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    path(
        'password-reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'password-reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),

    

    # path('', views.dashboard, name='dashboard'),
]

DjangoRed/DatasetViewApp/urls.py
from django.urls import path
from . import views

app_name = 'dataset_view'

urlpatterns = [
    path('list/', views.datasets_list_view, name='list'),
    path('details/', views.datasets_view, name='details'),
    path('details/<int:page>', views.datasets_view, name='details_page'),
    path('download/', views.download_csv, name='download'),
]

DjangoRed/DjangoRed/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HomeApp.urls', namespace="HomeApp")),
    path('', include('VisualizationApp.urls', namespace="VisualizationApp")),
    path('parser/', include('ParserApp.urls', namespace="ParserApp")),
    path('datasets/', include('DatasetViewApp.urls', namespace="DatasetViewApp")),
    path('users/', include('GraphApp.urls', namespace="GraphApp")),
    path('account/', include('AccountsApp.urls', namespace="AccountsApp")),
    path('statistic/', include('StatApp.urls', namespace="StatApp")),
]
from django.conf import settings
from django.conf.urls.static import static


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoRed/HomeApp/urls.py
from . import views
from django.urls import path

app_name = "HomeApp"
urlpatterns = [
    path('', views.home_view, name='home')
]

DjangoRed/VisualizationApp/urls.py
from . import views
from django.urls import path

app_name = "VisualizationApp"
urlpatterns = [
    path('visualization-app', views.visualization_app_view, name='visualization-app')
]

DjangoRed/templates/accounts/login.html
{% extends "base.html" %}
{% block title %}Log-in{% endblock %}
{% block content %}
   
    

    {% load widget_tweaks %}
    <div class="container content-padding">
        <h1 class="main-head">Log-in</h1>
        <div class="main-interface main-form">
            {% if form.errors %}
                <p>
                    Your username and password didn't match.
                    Please try again.
                </p>
            {% else %}
                <p>Please, use the following form to log-in:</p>
            {% endif %}
            <form action="{% url 'AccountsApp:login' %}" method="post">
                <label for="{{ login_form.username.id_for_label }}">Username</label><br>
                {% render_field login_form.username class="form-control btn active my-1 text-start" %}<br>
                
                <label for="{{ login_form.password.id_for_label }}">Password</label><br>
                {% render_field login_form.password class="form-control btn active my-1 text-start" %}<br>
                
                <!-- {{ login_form.as_p }} -->
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}" />
                <p><input type="submit" value="Log-in" class="parser-form-submit btn complete"></p>
            </form>
        </div>
    </div>
    
    
{% endblock %}

DjangoRed/templates/accounts/logout.html
{% extends "base.html" %}

{% block title %}Logged out{% endblock %}

{% block content %}
    <h1>Logged out</h1>
    <p>
        You have been successfully logged out.
        You can <a href="{% url 'AccountsApp:login' %}">log-in again</a>.
    </p>
{% endblock %}

DjangoRed/templates/accounts/password_change.html
{% extends "base.html" %}
{% block title %}Log-in{% endblock %}

{% load static %}

{% block custom_styles %}

    <link rel="stylesheet" href="{% static 'css/user/style.css' %}">

{% endblock %}

{% block content %}
   
    

    {% load widget_tweaks %}
    <div class="content-padding d-flex justify-content-end align-items-center full-height" >
        
        <div class="main-interface main-form" style="height: fit-content;">
            <h1 class="main-head">Change password</h1>
            {% if form.errors %}
                <p>
                    Your username and password didn't match.
                    Please try again.
                </p>
            {% else %}
                <p>Please, use the following form to log-in:</p>
            {% endif %}
            <form action="{% url 'AccountsApp:password_change_done' %}" method="post" >
                <label for="{{ pass_form.old_password.id_for_label }}">Old password</label><br>
                {% render_field pass_form.old_password class="form-control btn active my-1 text-start" %}<br>
                
                <label for="{{ pass_form.password1.id_for_label }}">New password</label><br>
                {% render_field pass_form.password1 class="form-control btn active my-1 text-start" %}<br>
                
                <label for="{{ pass_form.password2.id_for_label }}">Repeat new password</label><br>
                {% render_field pass_form.password1 class="form-control btn active my-1 text-start" %}<br>
                
                <!-- {{ pass_form.as_p }} -->
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}" />
                <p><input type="submit" value="Log-in" class="parser-form-submit btn complete"></p>
            </form>
        </div>
    </div>
    
    
{% endblock %}

DjangoRed/templates/accounts/password_change_done.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    {% block custom_styles %}
        <link rel="stylesheet" href="{% static 'css/parser/style.css' %}">
    {% endblock %}
</head>

<body>
    {% block content %}
    
    <div class="container-fluid">
        <div class="row mx-auto w-fit background-small">
            <p class="text display-4">Password changed</p><br>
        </div>
    </div>

    {% endblock %}
</body>

</html>

DjangoRed/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}
    {{ user.username }} profile 
{% endblock %}

{% load static %}

{% block scripts %}
    <link rel="stylesheet" href="{% static 'css/datasets/style.css' %}">
    <script src="{% static 'js/datasets/filter_datasets.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/user/style.css' %}">

{% endblock %}

{% block content %}
    <h1 class="main-head">{{ user.username }} profile</h1>
    {% load widget_tweaks %}
        <div class="">
            <div class="row d-flex justify-content-around align-items-center">
                <div class="main-interface user-page col-lg-3 col-md-5 col-sm-12">
                    <h2 class="text-center">User Image</h2>
                    <div class="img-container d-flex justify-content-center">
                        <img class="user-img" src="{% if user_image %}{{ user_image.url }}{% else %}{% static 'img/jokerge.png' %}{% endif %}">
                    </div>
                    <form method="post" action="{% url 'AccountsApp:profile' %}" enctype="multipart/form-data">
                        <div class="row d-flex">
                            <label  for="{{ change_image_form.image.id_for_label }}" class="m-2">Upload new image</label>
                            
                                {% render_field change_image_form.image id="image" class="m-2 form-control" type="file" id="formFile" %}
                            
                        </div>
                        {% csrf_token %}
                        <div class="user-info-item d-flex justify-content-end ">
                            <input type="submit" class="btn complete m-3" value="Change-image" name="Change-image">
                        </div>
                    </form>
                </div>
                <div class="main-interface col-lg-3 col-md-5  col-sm-12">
                    <h2 class="text-center">User Info</h2>
                    <div class="row user-info-item m-2">
                        <label class="col-4">Change Password?</label>
                        <div class="col-8">
                            <a class="btn complete m-3" href="{% url 'AccountsApp:password_change' %}">Change password</a>
                        </div>
                    </div>
                    <form method="post" action="{% url 'AccountsApp:profile' %}">
                        <div class="row user-info-item m-2">
                            <label class="col-4" for="{{ change_data_form.email.id_for_label }}">Email</label>
                            <div class="col-8">
                                {% render_field change_data_form.email id="email" class="form-input "  style="width:100%" %}
                            </div>
                        </div>

                        <div class="row user-info-item m-2">
                            <label class="col-4" for="{{ change_data_form.date_of_birth.id_for_label }}">Date of birth</label>
                            <div class="col-8">
                                {% render_field change_data_form.date_of_birth id="date_of_birth" class="form-input"  style="width:100%" %}
                            </div>
                        </div>
                        {% csrf_token %}
                        <div class="user-info-item d-flex justify-content-end ">
                            <input type="submit" class="btn complete m-3" value="Change-data" name="Change-data" >
                        </div>
                    </form>
                </div>
                <div class="main-interface col-lg-3 col-md-5  col-sm-12" >
                    <form method="post" onkeydown="return event.key != 'Enter'">
                        {% csrf_token %}
                        <div>
                            <h2 class="text-center">Favorite datasets</h2>
                            <div class="row">
                                <div class="col-lg-6 col-sm-12 right-vertical-rule ">
                                    <div class="my-1">
                                        <h4>Options:</h4>
                                        <div class="grid-buttons">
                                            <div><input type="submit" class="btn complete grid-button" formaction="{% url 'VisualizationApp:visualization-app'%}" value="cluster"></div>
                                            <div><input type="submit" class="btn complete grid-button" formaction="/statistic" value="statistic"></div>
                                            <div><input type="submit" class="btn complete grid-button" formaction="{% url 'DatasetViewApp:details'%}" value="view"></div>
                                            <div><input type="text" class="form-control w-75 my-3 filter-button-class" placeholder="search" data-set_type="comment_set"></div>
                                        </div>
                                    </div>
                                    
                                </div>
                                <div class="col-sm-12 col-lg-6">
                                    <h4 >Datasets:</h4>
                                    <div id="dataset-holder" class="my-1 scroll-list">
                                        {% if expired_job_ids|length > 0 %}
                                            <p>
                                                Following datasets were expired:
                                                {% for expired_dataset in expired_job_ids %}
                                                    {{ expired_dataset }}
                                                {% endfor %}
                                            </p>
                                        {% endif %}
                                        {% for favorite in up_to_date_job_ids %}
                                            <div>
                                                <input type="checkbox" name="{{favorite.job_id}}" id="{{favorite.job_id}}" class="mx-1" checked>
                                                <label for="{{favorite.job_id}}">{{ favorite }}</label>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                
            </div>
        </div>
   
    
    

{% endblock %}

DjangoRed/templates/accounts/register.html
{% extends "base.html" %}

{% block title %}Create an account{% endblock %}

{% load static %}

{% block custom_styles %}

    <link rel="stylesheet" href="{% static 'css/user/style.css' %}">

{% endblock %}

{% block content %}
    
    <div class="container content-padding d-flex justify-content-end align-items-center full-height">
        <div class="main-interface main-form login-form register-form">
            <h1 class="main-head">Register</h1>
            {% load widget_tweaks %}
            <form method="post">
                {% if form.errors %}
                    <p>
                        Your username and password didn't match.
                        Please try again.
                    </p>
                {% else %}
                    <p>Please, sign up using the following form:</p>
                {% endif %}

                <label for="{{ registration_form.username.id_for_label }}">Username</label><br>
                {% render_field registration_form.username class="form-control btn active my-1 text-start" %}<br>
                        
                <label for="{{ registration_form.email.id_for_label }}">Email</label><br>
                {% render_field registration_form.email class="form-control btn active my-1 text-start" %}<br>
                
                <label for="{{ registration_form.password1.id_for_label }}">Password</label><br>
                {% render_field registration_form.password1 class="form-control btn active my-1 text-start" %}<br>
                
                <label for="{{ registration_form.password2.id_for_label }}">Confirm password</label><br>
                {% render_field registration_form.password2 class="form-control btn active my-1 text-start" %}<br>
                
                <label for="{{ registration_form.date_of_birth.id_for_label }}">Date of birth (YYYY-MM-DD)</label><br>
                {% render_field registration_form.date_of_birth class="form-control btn active my-1 text-start" %}<br>
                
                <!-- {{ register_form.as_p }} -->
                {% csrf_token %}
                <p><input type="submit" value="Register" class="parser-form-submit btn complete"></p>
            </form>
        </div>
    </div>
    
{% endblock %}

DjangoRed/templates/accounts/register_done.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <h1>Welcome {{ new_user.first_name }}!</h1>
    <p>
    Your account has been successfully created.
    Now you can <a href="{% url 'AccountsApp:login' %}">log in</a>.
    </p>
{% endblock %}