DjangoRed/DatasetViewApp/urls.py
from django.urls import path
from . import views

app_name = 'dataset_view'

urlpatterns = [
    path('list/', views.datasets_list_view, name='list'),
    path('details/', views.datasets_view, name='details'),
    path('details/<int:page>', views.datasets_view, name='details_page'),
    path('download/', views.download_csv, name='download'),
]

DjangoRed/DjangoRed/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HomeApp.urls', namespace="HomeApp")),
    path('', include('VisualizationApp.urls', namespace="VisualizationApp")),
    path('parser/', include('ParserApp.urls', namespace="ParserApp")),
    path('datasets/', include('DatasetViewApp.urls', namespace="DatasetViewApp")),
    path('users/', include('GraphApp.urls', namespace="GraphApp")),
    path('account/', include('AccountsApp.urls', namespace="AccountsApp")),
    path('statistic/', include('StatApp.urls', namespace="StatApp")),
]
from django.conf import settings
from django.conf.urls.static import static


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoRed/GraphApp/urls.py
from django.urls import path
from . import views

app_name = 'GraphApp'

urlpatterns = [
    path('base_graph/', views.base_graph_view, name='base_graph'),
    path('base_graph_download/', views.download_graph, name='base_graph_download'),
]

DjangoRed/HomeApp/urls.py
from . import views
from django.urls import path

app_name = "HomeApp"
urlpatterns = [
    path('', views.home_view, name='home')
]

DjangoRed/StatApp/urls.py
from django.urls import path
from . import views

app_name = 'StatApp'

urlpatterns = [
    path('', views.stat_view, name='stat')
]

DjangoRed/VisualizationApp/urls.py
from . import views
from django.urls import path

app_name = "VisualizationApp"
urlpatterns = [
    path('visualization-app', views.visualization_app_view, name='visualization-app')
]

DjangoRed/templates/datasets/details.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% block scripts %}
        <script src="{% static 'js/datasets/dataset_details.js' %}"></script> 
        <link rel="stylesheet" href="{% static 'css/datasets/style.css' %}">
    {% endblock %}
</head>

<body>
    {% block content %}

    {% load widget_tweaks %}

    <form action="{% url 'DatasetViewApp:details' %}" method="post">
        {% csrf_token %}

        <div class="container-fluid">
            <div class="row">
                <div id="dataset-holder" class="my-1 background-small">
                    {% for dataset_id in dataset_ids %}
                        <div>
                            <input type="checkbox" name="{{dataset_id}}" id="{{dataset_id}}" class="mx-1" checked>
                            <label for="{{dataset_id}}">{{dataset_id}}</label>
                        </div>
                    {% endfor %}
                </div>
            </div>
            
            <div class="row">
                <div class="d-flex align-items-center">
                    <input type="text" class="form-control mx-1 trans-input" name="name-for-added-datasets" id="add-dataset-source">
                    <button type="button" class="btn active mx-1 grey-bkg" id="add-dataset">Add dataset</button>
                    <input type="submit" class="btn complete mx-1 grey-bkg" value="Recalculate datasets">
                    {% if downloadable %}
                        <button id="download-button-false" class="btn complete mx-1 grey-bkg" type="button">Download CSV</button>
                        <input formaction="{% url 'DatasetViewApp:download' %}" id="download-button-true" class="btn complete mx-1 grey-bkg" type="submit" value="Download CSV">
                    {% endif %}
                    <div class="d-flex justify-content-end w-100">
                        {% if previous_page %}
                            <input formaction="{% url 'DatasetViewApp:details_page' previous_page %}" class="btn complete mx-1 grey-bkg" type="submit" value="previous_page">
                        {% endif %}
                        {% if next_page %}
                            <input formaction="{% url 'DatasetViewApp:details_page' next_page %}" class="btn complete mx-1 grey-bkg" type="submit" value="next_page">
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

    </form>

    {% if not error %}
        <div class="container-fluid">
            <div class="d-flex flex-row flex-nowrap overflow-auto">
                <table class="table table-dark table-striped">
                    <thead>
                        {% for h in headers %}
                        <th>
                            {{h}}
                        </th>
                        {% endfor %}
                    </thead>
                    <tbody>
                        {% for row in data %}
                            <tr>
                                {% for cell in row %}
                                    <td>
                                        {{cell}}
                                    </td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% else %}
        <div class="container-fluid text-danger m-2">
            {{error}}
        </div>
    {% endif %}

    {% endblock %}
</body>

</html>

DjangoRed/templates/datasets/list.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% block scripts %}
        <script src="{% static 'js/datasets/filter_datasets.js' %}"></script> 
        {{ request.user.username|json_script:"user_id" }}
        <script src="{% static 'js/datasets/dataset_fav_socket.js' %}"></script> 
        <link rel="stylesheet" href="{% static 'css/datasets/style.css' %}">
    {% endblock %}
</head>

<body>
    
    {% block content %}

    {% load widget_tweaks %}

    <form method="post" onkeydown="return event.key != 'Enter'">
        {% csrf_token %}
        <div class="container-fluid">
            <div class="row background-border scrollbar">
                <div class="col-lg-2 col-sm-12 right-vertical-rule">
                    <div class="grid-buttons">
                        <h4>Options:</h4>
                        <div><input type="submit" class="btn complete grid-button grey-bkg w-100" formaction="{% url 'VisualizationApp:visualization-app'%}" value="cluster"></div>
                        <div><input type="submit" class="btn complete grid-button grey-bkg w-100" formaction="{% url 'StatApp:stat' %}" value="statistic"></div>
                        <div><input type="submit" class="btn complete grid-button grey-bkg w-100" formaction="{% url 'DatasetViewApp:details'%}" value="view"></div>
                        <div><input type="text" class="form-control grid-button trans-input w-100 my-3 filter-button-class" placeholder="search" data-set_type="comment_set"></div>
                    </div>
                </div>
                <div class="col-lg-9 col-sm-12 pos-rel">
                    <div class="d-flex flex-row flex-nowrap overflow-auto pos-rel scroll-cards">
                        {% for set in comment_sets %}
                            <div class="card m-2 card-class comment_set card-bkg">
                                <label for="{{set.0}}" class="label-pos">
                                    <img src="{% static 'img/comment.png' %}" class="card-img-top card-img-top-sizing" alt="comments">
                                    <div class="card-body scrollbar">
                                        <p class="card-text set-id">{{set.0}}</p>
                                        <p class="card-text px-2">{{set.1.type}}</p>
                                        <p class="card-text px-2 set-context">{{set.1.context}}</p>
                                        <p class="card-text">{{set.2}}</p>
                                    </div>
                                    <input type="checkbox" id="{{set.0}}" name="{{set.0}}"  class="checkbox-absolute list">
                                </label>
                                <div type="button" id="fav {{set.0}}" name ="fav {{set.0}}" class="button-absolute" onclick="send_data(this)"></div> 
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </form>

    <form method="post" onkeydown="return event.key != 'Enter'">
        {% csrf_token %}
        <div class="container-fluid">
            <div class="row background-border scrollbar">
                <div class="col-lg-2 col-sm-12 right-vertical-rule">
                    <div class="grid-buttons">
                        <h4>Options:</h4>
                        <div><input type="submit" class="btn complete grid-button grey-bkg w-100" formaction="{% url 'GraphApp:base_graph'%}" value="graph"></div>
                        <div><input type="submit" class="btn complete grid-button grey-bkg w-100" formaction="{% url 'DatasetViewApp:details'%}" value="view"></div>
                        <div><input type="text" class="form-control grid-button trans-input w-100 my-3 filter-button-class" placeholder="search" data-set_type="user_sets"></div>
                    </div>                    
                </div>
                <div class="col-lg-9 col-sm-12">
                    <div class="d-flex flex-row flex-nowrap overflow-auto scroll-cards">
                        {% for set in user_sets %}
                            <div class="card m-2 card-class user_sets card-bkg">
                                <label for="{{set.0}}" class="label-pos">
                                    <img src="{% static 'img/user.png' %}" class="card-img-top card-img-top-sizing" alt="users">
                                    <div class="card-body scrollbar">
                                        <p class="card-text set-id">{{set.0}}</p>
                                        <p class="card-text px-2">{{set.1.type}}</p>
                                        <p class="card-text px-2 set-context">{{set.1.context}}</p>
                                        <p class="card-text">{{set.2}}</p>
                                    </div>
                                    <input type="checkbox" id="{{set.0}}" name="{{set.0}}" class="checkbox-absolute list">
                                </label>
                                <div type="button" id="fav {{set.0}}" name ="fav {{set.0}}" class="button-absolute" onclick="send_data(this)"></div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div class="container-fluid overflow-auto">
        <div class="row">
            {% for set in favorite_sets %}

            {% endfor %}
        </div>
    </div>

    {% endblock %}
</body>

</html>