DjangoRed/DatasetViewApp/urls.py
from django.urls import path
from . import views

app_name = 'dataset_view'

urlpatterns = [
    path('list/', views.datasets_list_view, name='list'),
    path('details/', views.datasets_view, name='details'),
    path('details/<int:page>', views.datasets_view, name='details_page'),
    path('download/', views.download_csv, name='download'),
]

DjangoRed/DjangoRed/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HomeApp.urls', namespace="HomeApp")),
    path('', include('VisualizationApp.urls', namespace="VisualizationApp")),
    path('parser/', include('ParserApp.urls', namespace="ParserApp")),
    path('datasets/', include('DatasetViewApp.urls', namespace="DatasetViewApp")),
    path('users/', include('GraphApp.urls', namespace="GraphApp")),
    path('account/', include('AccountsApp.urls', namespace="AccountsApp")),
    path('statistic/', include('StatApp.urls', namespace="StatApp")),
]
from django.conf import settings
from django.conf.urls.static import static


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoRed/HomeApp/urls.py
from . import views
from django.urls import path

app_name = "HomeApp"
urlpatterns = [
    path('', views.home_view, name='home')
]

DjangoRed/ParserApp/urls.py
from django.urls import path
from . import views

app_name = 'parser'

urlpatterns = [
    path('start/', views.parser_interface_view, name='start'),
    path('report/', views.parser_intrepret_query, name='report'),
]

DjangoRed/templates/parser/interface.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% block scripts %}
        <script src="{% static 'js/parser/form_script.js' %}"></script> 
        <link rel="stylesheet" href="{% static 'css/parser/style.css' %}">
    {% endblock %}
</head>

<body>
    {% block content %}
        <div class="container-fluid my-5">
            <div class="row mx-auto">
                <div class="main-interface main-form">
                    <div class="parser-form-meta" style="display: none;">
                        <select class="btn active" id="parser-form-select">
                            <option value="submission_comments">submission comments</option>
                            <option value="subreddit_comments">subreddit comments</option>
                            <option value="subreddit_users">subreddit users</option>
                        </select>
                    </div>

                    <div class="container-fluid">
                        <div class="row">
                            <div class="col d-flex justify-content-center">
                                <p class="display-6 font-w">
                                    Parsing target
                                </p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col d-flex justify-content-center">
                                <ul class="nav nav-pills">
                                    <li class="nav-item target-btn target-btn-active m-1" id="submission_comments">
                                        submission comments
                                    </li>
                                    <li class="nav-item target-btn m-1" id="subreddit_comments">
                                        subreddit comments
                                    </li>
                                    <li class="nav-item target-btn m-1" id="subreddit_users">
                                        subreddit users
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    {% load widget_tweaks %}

                    <div class="parser-form-comments-submission parser-form-option main-bkg mt-5 p-2">
                        <form action="{% url 'ParserApp:report' %}" method="post">
                            {% csrf_token %} 
                            <div>
                                <label for="{{ submission_parsing_form.target.id_for_label }}" class="mt-3 mb-1">Url of submission</label><br>
                                <div class="d-flex justify-content-between">
                                    <div class="w-70">    
                                        {% render_field submission_parsing_form.submission_url id="ephemeral-submission-input" class="form-control btn active text-start w-100 mb-1 trans-input" %}
                                    </div>
                                    <div class="w-27 pos-rel">
                                        <input type="button" value="Add more" class="form-add-more btn active grey-bkg mb-1 w-100 pm-0" data-ephemeral="ephemeral-submission">
                                    </div>
                                </div>
                            </div>
                            <div>
                                <div id="ephemeral-submission-div" class="grid-buttons ">

                                </div>
                            </div>

                            <label for="{{ submission_parsing_form.target.id_for_label }}" class="mt-3 mb-1">How deep to parse threads</label><br>
                            {% render_field submission_parsing_form.comment_replace_limit class="btn active align-left w-100 trans-input" %}<br>

                            <label for="{{ submission_parsing_form.target.id_for_label }}" class="mt-3 mb-1">Minimum depth of thread to parse deeper</label><br>
                            {% render_field submission_parsing_form.comment_replace_threshold class="btn active align-left w-100 trans-input" %} <br>

                            {{submission_parsing_form.form_type}}<br>

                            <div class="d-flex justify-content-center">
                                <input type="submit" class="parser-form-submit btn complete grey-bkg send-btn-w" value="send" data-ephemeral="ephemeral-submission">
                            </div>
                        </form>
                    </div>

                    <div class="parser-form-comments-subreddit parser-form-option main-bkg mt-5 p-2">
                        <form action="{% url 'ParserApp:report' %}" method="post">
                            {% csrf_token %} 

                            <div>
                                <label for="{{ subreddit_parsing_form.target.id_for_label }}" class="mt-3 mb-1">Subreddit name</label><br>
                                <div class="d-flex justify-content-between">
                                    <div class="w-70">    
                                        {% render_field subreddit_parsing_form.subreddit_name id="ephemeral-sub-comment-input" class="btn active text-start w-100 mb-1 trans-input" %}
                                    </div>
                                    <div class="w-27 pos-rel">
                                        <input type="button" value="Add more" class="form-add-more btn active grey-bkg mb-1 w-100 pm-0" data-ephemeral="ephemeral-sub-comment">
                                    </div>
                                </div>
                            </div>
                            <div>
                                <div id="ephemeral-sub-comment-div">

                                </div>
                            </div>

                            <label for="{{ subreddit_parsing_form.target.id_for_label }}" class="mt-3 mb-1">In-subreddit query</label><br>
                            {% render_field subreddit_parsing_form.subreddit_query class="btn active text-start w-100 mb-1 trans-input" %}<br>

                            <label for="{{ subreddit_parsing_form.target.id_for_label }}" class="mt-3 mb-1">Sort recency</label><br>
                            {% render_field subreddit_parsing_form.time_filter class="btn active w-100 mb-1 trans-input" %}<br>

                            <label for="{{ subreddit_parsing_form.target.id_for_label }}" class="mt-3 mb-1">Sort type</label><br>
                            {% render_field subreddit_parsing_form.subreddit_sort class="btn active w-100 mb-1 trans-input" %}<br>

                            <label for="{{ subreddit_parsing_form.target.id_for_label }}" class="mt-3 mb-1">Maximum search items</label><br>
                            {% render_field subreddit_parsing_form.search_limit class="btn active w-100 mb-1 trans-input" %}<br>

                            <label for="{{ subreddit_parsing_form.target.id_for_label }}" class="mt-3 mb-1">How deep to parse threads</label><br>
                            {% render_field subreddit_parsing_form.comment_replace_limit class="btn active w-100 mb-1 trans-input" %}<br>

                            <label for="{{ subreddit_parsing_form.target.id_for_label }}" class="mt-3 mb-1">Minimum depth of thread to parse deeper</label><br>
                            {% render_field subreddit_parsing_form.comment_replace_threshold class="btn active w-100 mb-1 trans-input" %} <br>

                            {{subreddit_parsing_form.form_type}}<br>
                            
                            <div class="d-flex justify-content-center">
                                <input type="submit" class="parser-form-submit btn complete grey-bkg send-btn-w" value="send" data-ephemeral="ephemeral-sub-comment">
                            </div>
                        </form>
                    </div>

                    <div class="parser-form-users parser-form-option main-bkg mt-5 p-2">
                        <form action="{% url 'ParserApp:report' %}" method="post">
                            {% csrf_token %} 

                            <div>
                                <label for="{{ subreddit_users_parsing_form.multi_subreddit_name.id_for_label }}" class="mt-3 mb-1">Source subreddits</label><br>
                                <div class="d-flex justify-content-between">
                                    <div class="w-70">    
                                        {% render_field subreddit_users_parsing_form.multi_subreddit_name id="ephemeral-users-input" class="btn active text-start w-100 mb-1 trans-input" %}
                                    </div>
                                    <div class="w-27 pos-rel">
                                        <input type="button" value="Add more" class="form-add-more btn active grey-bkg mb-1 w-100 pm-0" data-ephemeral="ephemeral-users">
                                    </div>
                                </div>
                            </div>

                            <div>
                                <div id="ephemeral-users-div">

                                </div>
                            </div>

                            <label for="{{ subreddit_users_parsing_form.target.id_for_label }}" class="mt-3 mb-1">Sort discipline</label><br>
                            {% render_field subreddit_users_parsing_form.subreddit_sort_exclusive class="btn active w-100 mb-1 trans-input" %}<br>

                            <label for="{{ subreddit_users_parsing_form.target.id_for_label }}" class="mt-3 mb-1">Maximum search items</label><br>
                            {% render_field subreddit_users_parsing_form.search_limit class="btn active w-100 mb-1 trans-input" %}<br>

                            <label for="{{ subreddit_users_parsing_form.target.id_for_label }}" class="mt-3 mb-1">How deep to parse threads</label><br>
                            {% render_field subreddit_users_parsing_form.comment_replace_limit class="btn active w-100 mb-1 trans-input" %}<br>

                            <label for="{{ subreddit_users_parsing_form.target.id_for_label }}" class="mt-3 mb-1">Minimum depth of thread to parse deeper</label><br>
                            {% render_field subreddit_users_parsing_form.comment_replace_threshold class="btn active w-100 mb-1 trans-input" %} <br>

                            {{subreddit_users_parsing_form.form_type}}<br>

                            <div class="d-flex justify-content-center">
                                <input type="submit" class="parser-form-submit btn complete grey-bkg send-btn-w" value="send" data-ephemeral="ephemeral-users">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
</body>

</html>

DjangoRed/templates/parser/report.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    {% block custom_styles %}
        <link rel="stylesheet" href="{% static 'css/parser/style.css' %}">
    {% endblock %}
</head>

<body>
    {% block content %}
    
    <div class="container-fluid main-bkg b-1-w">
        <!--
        <div class="row mx-auto w-fit background-small">
            <p class="text display-4">Ok</p><br>
            <p class="text">Generated job_id: {{job_id}}</p><br>
            <p class="text display-6"><a href="{% url 'HomeApp:home' %}">Home</a></p><br>
            <p class="text display-6"><a href="{% url 'DatasetViewApp:list' %}">Check parsed datasets</a></p><br>
            <p class="text display-6"><a href="{% url 'ParserApp:start' %}">Parse more</a></p>
        </div>
        -->
        <div class="row">
            <div class="col d-flex justify-content-center">
                <p class="display-6">Ok. Generated job_id: {{job_id}}</p>
            </div>
        </div>
        <div class="row">
            <div class="col m-3 grey-bkg result-blob pos-rel">
                <P class="large-text">Save identifier to check the results later on datasets page. Or explore other saved datasets</P>
                <a href="{% url 'DatasetViewApp:list' %}" class="btn btn-outline-light btn-bottom-left">To dataset page</a>
                <img src="{% static 'img/parser/save_id.png' %}" class="img-abs img-offset">
            </div>
            <div class="col m-3 grey-bkg result-blob pos-rel">
                <p class="large-text">Learn more about the app.</p>
                <a href="#" class="btn btn-outline-light btn-bottom-left">Go to tutorials</a>
                <img src="{% static 'img/parser/intelligence.png' %}" class="img-abs">
            </div>
        </div>
        <div class="row">
            <div class="col m-3 grey-bkg result-blob pos-rel">
                <p class="large-text">Parse some more.</p>
                <a href="{% url 'ParserApp:start' %}" class="btn btn-outline-light btn-bottom-left">To parser page</a>
            </div>
            <div class="col m-3 grey-bkg result-blob pos-rel">
                <p class="large-text">Remember to have a nice day!</p>
                <img src="{% static 'img/parser/have_a_nice.png' %}" class="img-abs img-offset">
            </div>
        </div>
    </div>

    {% endblock %}
</body>

</html>