DjangoRed/AccountsApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts_app'

urlpatterns = [
    path('profile/', views.user_profile, name='profile'),
    path('register/', views.register, name='register'),

    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    # change password urls
    path(
        'password-change/',
        views.password_change,
        name='password_change'
    ),
    path(
        'password-change/done/',
        views.password_change_done,
        name='password_change_done'
    ),

    # reset password urls
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'
    ),
    path(
        'password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    path(
        'password-reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'password-reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),

    

    # path('', views.dashboard, name='dashboard'),
]

DjangoRed/DjangoRed/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HomeApp.urls', namespace="HomeApp")),
    path('', include('VisualizationApp.urls', namespace="VisualizationApp")),
    path('parser/', include('ParserApp.urls', namespace="ParserApp")),
    path('datasets/', include('DatasetViewApp.urls', namespace="DatasetViewApp")),
    path('users/', include('GraphApp.urls', namespace="GraphApp")),
    path('account/', include('AccountsApp.urls', namespace="AccountsApp")),
    path('statistic/', include('StatApp.urls', namespace="StatApp")),
]
from django.conf import settings
from django.conf.urls.static import static


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoRed/GraphApp/urls.py
from django.urls import path
from . import views

app_name = 'GraphApp'

urlpatterns = [
    path('base_graph/', views.base_graph_view, name='base_graph'),
    path('base_graph_download/', views.download_graph, name='base_graph_download'),
]

DjangoRed/HomeApp/urls.py
from . import views
from django.urls import path

app_name = "HomeApp"
urlpatterns = [
    path('', views.home_view, name='home')
]

DjangoRed/ParserApp/urls.py
from django.urls import path
from . import views

app_name = 'parser'

urlpatterns = [
    path('start/', views.parser_interface_view, name='start'),
    path('report/', views.parser_intrepret_query, name='report'),
]

DjangoRed/StatApp/urls.py
from django.urls import path
from . import views

app_name = 'StatApp'

urlpatterns = [
    path('', views.stat_view, name='stat')
]

DjangoRed/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Reddit Analysis{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/base/main.css' %}">
    {% block scripts %}
    {% endblock %}

    {% block custom_styles %}
    {% endblock %}

    {% block styles %}
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    {% endblock %}
</head>
<body>
    {% block header %}
    <nav class="navbar-main navbar-vertical">
        <a class="navbar-profile d-flex flex-column" href="{% url 'AccountsApp:profile' %}" >
            <img class="profile-img justify-content-md-center" src="{% if user.image %}{{ user.image.url }}{% else %}{% static 'img/jokerge.png' %}{% endif %}" alt="joker">
            
        </a>
        <ul class="navbar-list">
            {% if request.path == '/' %}
                <li class="nav-item nav-item-active active">
                    <a href="{% url 'HomeApp:home' %}">Home</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'HomeApp:home' %}">Home</a>
                </li>
            {% endif %}
            <hr>
            {% if 'visualization-app' in request.path %}
                <li class="nav-item nav-item-active active">
                    <a href="{% url 'VisualizationApp:visualization-app' %}">3D Cluster</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'VisualizationApp:visualization-app' %}">3D Cluster</a>
                </li>
            {% endif %}
            
            <hr>

            {% if 'parser' in request.path %}
                <li class="nav-item nav-item-active active">
                    <a href="{% url 'ParserApp:start' %}">Parser</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'ParserApp:start' %}">Parser</a>
                </li>
            {% endif %}

            <hr>

            {% if 'datasets' in request.path %}
            <li class="nav-item nav-item-active active">
                <a href="{% url 'DatasetViewApp:list' %}">Datasets</a>
            </li>
            {% else %}
                <li class="nav-item ">
                    <a href="{% url 'DatasetViewApp:list' %}">Datasets</a>
                </li>
            {% endif %}

            <hr>
            {% if 'graph' in request.path %}
            <li class="nav-item nav-item-active active">
                <a href="{% url 'GraphApp:base_graph' %}">Graph</a>
            </li>
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'GraphApp:base_graph' %}">Graph</a>
                </li>
            {% endif %}
            <hr>
            {% if 'statistic' in request.path %}
            <li class="nav-item nav-item-active active">
                <a href="{% url 'StatApp:stat' %}">Statistics</a>
            </li>
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'StatApp:stat' %}">Statistics</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    <div class="navbar-main navbar-horizontal">
        {% if user.is_authenticated %}
                <a class="nav-link dropdown-toggle navbar-text" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Welcome, {{ user.username }}
                </a>
                <ul class="dropdown-menu">
                    <li><a href=" {% url 'AccountsApp:profile' %} ">Profile</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a href=" {% url 'AccountsApp:logout' %} ">Log out</a></li>
                </ul>
            {% else %}
                <a class="nav-link dropdown-toggle navbar-text" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    You are not registred
                </a>
                <ul class="dropdown-menu">
                    <li><a href=" {% url 'AccountsApp:login' %} ">Login</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a href=" {% url 'AccountsApp:register' %} ">Sign up</a></li>
                </ul>
            {% endif %}
    </div>
    {% endblock %}

    <div class="main-content">
        
        {% block content %}
    
        {% endblock %}
    </div>
    
    {% block footer %}
    {% endblock %}
</body>
</html>

DjangoRed/templates/home.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% block content %}
       <div class="container-fluid">
            
            {% load static %}
            <h1 class="main-head" id="list">Home page</h1>
            <div class="row">
                <div class="main-interface" style="height: fit-content;">
                    <h3 class="main-head">Tutorials</h3>
                    <div class="d-flex flex-row justify-content-center">
                        <ul class="link-list">
                            <li class="m-3">
                                <a href="#parser">Parser tutorial</a>
                            </li>
                            <li class="m-3">
                                <a href="#datasets">Datasets tutorial</a>
                            </li>
                            <li class="m-3">
                                <a href="#cluster">Cluster tutorial</a>
                            </li>
                            <li class="m-3">
                                <a href="#stat">Statistics tutorial</a>
                            </li>
                            <li class="m-3">
                                <a href="#graph">Graph tutorial</a>
                            </li>
                            <li class="m-3">
                                <a href="#profile">Profile tutorial</a>
                            </li>
                        </ul>
                    </div>
                   
                </ul>
                </div>
                <div class="main-interface">
                    <div class="d-flex flex-column justify-content-center align-items-center">
                        
                        <h2 id="parser">Parser tutorial (<a href="#list">back to top</a>)</h2>
                        <video  class="main-video" controls>
                            <source src="{% static "videos/parser.mp4" %}" type="video/mp4"></source>
                            Your browser does not support the video tag
                        </video>
                        <hr>
                        <h2 id="datasets">Datasets tutorial (<a href="#list">back to top</a>)</h2>
                        <video class="main-video" controls>
                            <source src="{% static "videos/datasets.mp4" %}" type="video/mp4"></source>
                            Your browser does not support the video tag
                        </video>
                        <hr>
                        <h2 id="cluster">Cluster tutorial (<a href="#list">back to top</a>)</h2>
                        <video class="main-video" controls>
                            <source src="{% static "videos/cluster.mp4" %}" type="video/mp4"></source>
                            Your browser does not support the video tag
                        </video>
                        <hr>
                        <h2 id="stat">Statistic tutorial (<a href="#list">back to top</a>)</h2>
                        <video class="main-video" controls>
                            <source src="{% static "videos/stat.mp4" %}" type="video/mp4"></source>
                            Your browser does not support the video tag
                        </video>
                        <h2 id="graph">Graph tutorial (<a href="#list">back to top</a>)</h2>
                        <video class="main-video" controls>
                            <source src="{% static "videos/graph.mp4" %}" type="video/mp4"></source>
                            Your browser does not support the video tag
                        </video>
                        <hr>
                        <h2 id="profile">Profile tutorial (<a href="#list">back to top</a>)</h2>
                        <video class="main-video" controls>
                            <source src="{% static "videos/profile.mp4" %}" type="video/mp4"></source>
                            Your browser does not support the video tag
                        </video>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
</body>

</html>

DjangoRed/templates/index.html
{% extends 'base.html' %}



<!DOCTYPE html>
<html lang="en-us">
  {% load static %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Unity WebGL Player | RedditGraphs3D</title>

    {% block styles %}
    <link rel="stylesheet" href="{% static 'css/cluster/style.css' %}">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="shortcut icon" href="{% static 'unity/TemplateData/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'unity/TemplateData/style.css' %}">
    {% endblock %}
    
    {% block scripts %}
      <script src="{% static 'js/visualization_app/visualization-socket.js' %}"></script> 
      <script src="{% static 'js/visualization_app/dataset_check.js' %}"></script> 
    {% endblock %}
    
  </head>
  <body>
    {% block content %}
    
      
      {% load widget_tweaks %}
      <div class="container ">
        
        <button id="imitate-button" onclick="ImitateDotTextProcess()" style="display: none;">keke</button>
        <div class="main-interface">
          <h1 class="main-head ">3D cluster visualization app</h1>
          <form method="post" id="vis-app-form" class="form-inline m-4">
            <div class="row" id="main-form-clust">
              <div class="col-lg-3 col-md-6 d-flex flex-column right-vertical-rule">
                
                <div class="row" >  
                  <h5 class="col-lg-6 col-md-12">Dataset selection</h5>
                  <a class="dropdown-toggle col-lg-6 col-md-12 dataset-dropdown" id="form-header" role="button" data-bs-toggle="dropdown" >
                    No datasets selected
                  </a>
                  <ul class="dropdown-menu " id="dataset-holder" style="width: 200px;">
                    {% for dataset_id in dataset_ids %}
                      <li>
                        <input class="dataset_id" type="checkbox" name="{{dataset_id}}" id="{{dataset_id}}" checked>
                        <label for="{{dataset_id}}">{{dataset_id}}</label>
                      </li>
                    {% endfor %}
                  </ul>
                </div>
                
                  <div class="row">
                    <div class="col-lg-6 col-md-12">
                      <input type="text" class="form-input" name="name-for-added-datasets" id="add-dataset-source" style="width: 100%;" contentEditable="true">
                    </div>
                    <div class="col-lg-6 col-md-12">
                      <button type="button" class="btn active cluster-color fit-content" id="add-dataset">Add dataset</button>
                    </div>
                  </div>
                  
              </div>
              
              <div class="col-xl-2 col-lg-3 col-md-6 d-flex flex-column right-vertical-rule">
                  <label class="form-field" for="{{ visualization_form.clasterization_method.id_for_label }}">Clusterization method</label>
                  {% render_field visualization_form.clasterization_method id="clasterization-input" class="clasterization_params btn cluster-color fit-content"   %}
              </div>
              <div class="col-xl-1 col-lg-3 col-md-6 d-flex flex-column right-vertical-rule">
                  <label class="form-field" for="{{ visualization_form.clasters_count.id_for_label }}">Clusters count</label>
                  {% render_field visualization_form.clasters_count id="clasters-count-input" class="clasterization_params btn cluster-color " style="width: 65px" %}
              </div>
              <div class="col-xl-2 col-lg-3 col-md-6 d-flex flex-column right-vertical-rule">
  
                  <label class="form-field" for="{{ visualization_form.language.id_for_label }}">Language</label>
                  
                  {% render_field visualization_form.language id="language-input" class="clasterization_params btn cluster-color fit-content" %}
              </div>
              <div class="col-xl-2 col-lg-3 col-md-6 d-flex flex-column right-vertical-rule">
                <label class="form-field" for="{{ visualization_form.downsising_method.id_for_label }}">Downsizing method</label>
                {% render_field visualization_form.downsising_method id="downsising-input" class="clasterization_params btn cluster-color fit-content" %}
            
              </div>
              <div class="col-xl-2 col-lg-3 col-md-6 d-flex flex-column ">
                  <label class="form-field" for="{{ visualization_form.measure_of_distance.id_for_label }}">Measure of distance</label>
                  {% render_field visualization_form.measure_of_distance id="measure-input" class="clasterization_params btn cluster-color fit-content" %}
              </div>
              <div class="row form-field">
                <div class="col d-flex justify-content-center">
                  {% csrf_token %}
                  <input type="button" class="btn complete complete-button m-2" value="Load" style="width: 200px;" onclick="createString()">
                </div>
              </div>
          </form>
          <div style="width: 960px; height: 600px; padding: 100px;">
            <div id="unity-container" class="unity-desktop" >
              <canvas id="unity-canvas" width=960 height=600 tabindex="-1" ></canvas>
              <div id="unity-loading-bar">
                <div id="unity-logo"></div>
                <div id="unity-progress-bar-empty">
                  <div id="unity-progress-bar-full"></div>
                </div>
              </div>
              <div id="unity-warning"> </div>
              <div id="unity-footer">
                <div id="unity-webgl-logo"></div>
                <div id="unity-fullscreen-button"></div>
                <div id="unity-build-title">RedditGraphs3D</div>
              </div>
            </div>
          </div>
          
        </div>
        
      

          
        
        
      
    <script>

      var container = document.querySelector("#unity-container");
      var canvas = document.querySelector("#unity-canvas");
      var loadingBar = document.querySelector("#unity-loading-bar");
      var progressBarFull = document.querySelector("#unity-progress-bar-full");
      var fullscreenButton = document.querySelector("#unity-fullscreen-button");
      var warningBanner = document.querySelector("#unity-warning");

      // Shows a temporary message banner/ribbon for a few seconds, or
      // a permanent error message on top of the canvas if type=='error'.
      // If type=='warning', a yellow highlight color is used.
      // Modify or remove this function to customize the visually presented
      // way that non-critical warnings and error messages are presented to the
      // user.
      function unityShowBanner(msg, type) {
        function updateBannerVisibility() {
          warningBanner.style.display = warningBanner.children.length ? 'block' : 'none';
        }
        var div = document.createElement('div');
        div.innerHTML = msg;
        warningBanner.appendChild(div);
        if (type == 'error') div.style = 'background: red; padding: 10px;';
        else {
          if (type == 'warning') div.style = 'background: yellow; padding: 10px;';
          setTimeout(function() {
            warningBanner.removeChild(div);
            updateBannerVisibility();
          }, 5000);
        }
        updateBannerVisibility();
      }
      
      // var buildUrl = "../static/unity/Build";
      var buildUrl = "{% static 'unity/Build' %}";
      // var loaderUrl = buildUrl + "/Test Build.loader.js";
      var loaderUrl = "{% static 'js/unity_build/Test Build.loader.js' %}";
      var config = {
        // dataUrl: buildUrl + "/Test Build.data.gz",
        // frameworkUrl: buildUrl + "/Test Build.framework.js.gz",
        // codeUrl: buildUrl + "/Test Build.wasm.gz",
        dataUrl: "{% static 'unity/Build/Test Build.data.unityweb' %}",
        frameworkUrl: "{% static 'unity/Build/Test Build.framework.js.unityweb' %}",
        codeUrl: "{% static 'unity/Build/Test Build.wasm.unityweb' %}",
        streamingAssetsUrl: "StreamingAssets",
        companyName: "DefaultCompany",
        productName: "RedditGraphs3D",
        productVersion: "0.1",
        showBanner: unityShowBanner,
      };

      // By default Unity keeps WebGL canvas render target size matched with
      // the DOM size of the canvas element (scaled by window.devicePixelRatio)
      // Set this to false if you want to decouple this synchronization from
      // happening inside the engine, and you would instead like to size up
      // the canvas DOM size and WebGL render target sizes yourself.
      // config.matchWebGLToCanvasSize = false;

      if (/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)) {
        // Mobile device style: fill the whole browser client area with the game canvas:

        var meta = document.createElement('meta');
        meta.name = 'viewport';
        meta.content = 'width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, shrink-to-fit=yes';
        document.getElementsByTagName('head')[0].appendChild(meta);
        container.className = "unity-mobile";
        canvas.className = "unity-mobile";

        // To lower canvas resolution on mobile devices to gain some
        // performance, uncomment the following line:
        // config.devicePixelRatio = 1;


      } else {
        // Desktop style: Render the game canvas in a window that can be maximized to fullscreen:

        canvas.style.width = "960px";
        canvas.style.height = "600px";
      }

      loadingBar.style.display = "block";

      var script = document.createElement("script");
      script.src = loaderUrl;
      script.onload = () => {
        createUnityInstance(canvas, config, (progress) => {
          progressBarFull.style.width = 100 * progress + "%";
              }).then((unityInstance) => {
                loadingBar.style.display = "none";
                fullscreenButton.onclick = () => {
                  unityInstance.SetFullscreen(1);
                };
                gameInstance = unityInstance;
              }).catch((message) => {
                alert(message);
              });
            };

      document.body.appendChild(script);

    </script>
    {% endblock %}
  </body>
</html>